// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO accounts( Name, email, Role, APIkey)
VALUES($1, $2, $3, 
encode(sha256(random()::text::bytea),'hex'))
RETURNING id, name, email, role, apikey
`

type CreateUserParams struct {
	Name  string
	Email string
	Role  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Email, arg.Role)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Apikey,
	)
	return i, err
}

const getUserbyAPI = `-- name: getUserbyAPI :one
SELECT id, name, email, role, apikey from accounts where APIKey = $1
`

func (q *Queries) getUserbyAPI(ctx context.Context, apikey string) (Account, error) {
	row := q.db.QueryRowContext(ctx, getUserbyAPI, apikey)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Apikey,
	)
	return i, err
}
