// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO accounts( Name, email, Role)
VALUES($1, $2, $3)
RETURNING id, name, email, role, apikey
`

type CreateUserParams struct {
	Name  string
	Email string
	Role  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Name, arg.Email, arg.Role)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Role,
		&i.Apikey,
	)
	return i, err
}
