// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package database

import (
	"context"
	"database/sql"
)

const createApplications = `-- name: CreateApplications :one
INSERT INTO applications( department, status, company, position, interviewId)
VALUES($1, $2, $3,$4, $5)
RETURNING id, department, status, company, position, interviewid, date_applied
`

type CreateApplicationsParams struct {
	Department  string
	Status      string
	Company     int32
	Position    int32
	Interviewid sql.NullInt32
}

func (q *Queries) CreateApplications(ctx context.Context, arg CreateApplicationsParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, createApplications,
		arg.Department,
		arg.Status,
		arg.Company,
		arg.Position,
		arg.Interviewid,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.Department,
		&i.Status,
		&i.Company,
		&i.Position,
		&i.Interviewid,
		&i.DateApplied,
	)
	return i, err
}
