// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: interviews.sql

package database

import (
	"context"
	"time"
)

const createInterviews = `-- name: CreateInterviews :one
INSERT INTO interviews( status, interviewDate)
VALUES ($1, $2)
RETURNING id, status, interviewdate
`

type CreateInterviewsParams struct {
	Status        string
	Interviewdate time.Time
}

func (q *Queries) CreateInterviews(ctx context.Context, arg CreateInterviewsParams) (Interview, error) {
	row := q.db.QueryRowContext(ctx, createInterviews, arg.Status, arg.Interviewdate)
	var i Interview
	err := row.Scan(&i.ID, &i.Status, &i.Interviewdate)
	return i, err
}
