// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: job.sql

package database

import (
	"context"
)

const createJobs = `-- name: CreateJobs :one
INSERT INTO jobs( positionName, companyId, experienceRequired, expectedCompensation, employmentType, jobLocationType)
VALUES($1, $2, $3, $4, $5, $6)
RETURNING postionid, positionname, companyid, experiencerequired, expectedcompensation, employmenttype, joblocationtype
`

type CreateJobsParams struct {
	Positionname         string
	Companyid            int32
	Experiencerequired   string
	Expectedcompensation string
	Employmenttype       string
	Joblocationtype      string
}

func (q *Queries) CreateJobs(ctx context.Context, arg CreateJobsParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, createJobs,
		arg.Positionname,
		arg.Companyid,
		arg.Experiencerequired,
		arg.Expectedcompensation,
		arg.Employmenttype,
		arg.Joblocationtype,
	)
	var i Job
	err := row.Scan(
		&i.Postionid,
		&i.Positionname,
		&i.Companyid,
		&i.Experiencerequired,
		&i.Expectedcompensation,
		&i.Employmenttype,
		&i.Joblocationtype,
	)
	return i, err
}
